version: '3'
services:
  main_service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"