version: '3'
services:
  django:
    build: .
    working_dir: /app/G8word
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    working_dir: /app/G8word
    command: python -m celery -A G8word worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
      # - /app/G8word/
    depends_on:
      - redis