# Generated by Django 4.2.2 on 2023-07-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_record',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=33)),
                ('groupId', models.CharField(max_length=33)),
                ('message', models.TextField()),
                ('filtered_message', models.TextField(null=True)),
                ('mention', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='chat_record_mention',
            fields=[
                ('id', models.CharField(max_length=56, primary_key=True, serialize=False)),
                ('mentioned_userId', models.CharField(max_length=33, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linebot_app.chat_record')),
            ],
        ),
    ]
