# Generated by Django 4.2.2 on 2023-07-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='line_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='line_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=33)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue_process_app.line_user')),
            ],
        ),
    ]
